---
# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default: all rules enabled
default: true

# MD001 - Heading levels should only increment by one level at a time
MD001: true

# MD003 - Heading style (atx style: # Heading)
MD003:
  style: atx

# MD004 - Unordered list style (dash)
MD004:
  style: dash

# MD007 - Unordered list indentation (2 spaces)
MD007:
  indent: 2
  start_indented: false

# MD009 - No trailing spaces (except in code blocks for line breaks)
MD009:
  br_spaces: 2
  strict: false

# MD010 - No hard tabs
MD010:
  code_blocks: false

# MD012 - No multiple consecutive blank lines
MD012:
  maximum: 1

# MD013 - Line length (disabled - too strict for documentation)
MD013: false

# MD022 - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024 - No duplicate headings (disabled - common in large docs)
MD024: false

# MD025 - Single H1 per document
MD025: true

# MD026 - No trailing punctuation in headings
MD026:
  punctuation: ".,;:!。，；：！"

# MD029 - Ordered list item prefix
# Disabled: existing files use sequential numbering (1, 2, 3)
MD029: false

# MD030 - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD031 - Fenced code blocks should be surrounded by blank lines
MD031:
  list_items: true

# MD032 - Lists should be surrounded by blank lines
MD032: true

# MD033 - Allow inline HTML (common in READMEs)
MD033:
  allowed_elements:
    - br
    - details
    - summary
    - kbd
    - sup
    - sub
    - img
    - a
    - p
    - div
    - span
    - table
    - thead
    - tbody
    - tr
    - th
    - td

# MD034 - No bare URLs
MD034: true

# MD035 - Horizontal rule style (consistent)
MD035:
  style: "---"

# MD036 - No emphasis used instead of heading (disabled - common in READMEs)
MD036: false

# MD037 - No spaces inside emphasis markers
MD037: true

# MD038 - No spaces inside code span elements
MD038: true

# MD039 - No spaces inside link text
MD039: true

# MD040 - Fenced code blocks should have a language specified
# Disabled: many existing blocks without language
MD040: false

# MD041 - First line should be a top-level heading
MD041:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"

# MD044 - Proper names should have correct capitalization
MD044:
  names:
    - AWS
    - Python
    - GitHub
    - CLI
    - API
  code_blocks: false

# MD045 - Images should have alternate text
MD045: true

# MD046 - Code block style (fenced)
MD046:
  style: fenced

# MD047 - Files should end with a single newline character
MD047: true

# MD048 - Code fence style (backtick)
MD048:
  style: backtick

# MD049 - Emphasis style (asterisk)
MD049:
  style: asterisk

# MD050 - Strong style (asterisk)
MD050:
  style: asterisk

# MD051 - Link fragments should be valid
MD051: true

# MD052 - Reference links and images should use a label that is defined
MD052: true

# MD053 - Link and image reference definitions should be needed
MD053:
  ignored_definitions:
    - "//"
